project_name: "xiaobeir1"
# exp: "Qwen2.5-7B-Instruct-10iter-100steps"
exp: "debug"
# exp: "xiaobeir1-Qwen2.5-0.5B-Instruct"
# exp: "xiaobeir1-Qwen2.5-7B-Instruct"
# exp: "xiaobeir1-Qwen2.5-32B-Instruct"
# exp: "xiaobeir1-Qwen2.5-14B-Instruct"
# exp: "internlm/internlm2_5-1_8b"
# exp: "meta-llama/Llama-3.1-8B-Instruct"


random_seed: 42
evaluation_before_grpo: False
evaluation_after_grpo: False

eval_checkpoint_step: 540

model:
  # name: "Qwen/Qwen2.5-0.5B-Instruct"
  name: "Qwen/Qwen2.5-7B-Instruct"
  # name: "Qwen/Qwen2.5-14B-Instruct"
  # name: "Qwen/Qwen2.5-32B-Instruct"
  # name: "internlm/internlm2_5-1_8b"
  # name: "meta-llama/Llama-3.1-8B-Instruct"
  torch_dtype: "bfloat16"
  device_map: null

# gpu 2 batch 1 => 1step = 2item
training:
  use_lora: True
  continue_training: False
  current_step: 0
  num_iterations: 10
  steps_per_iteration: 100
  batch_size: 1
  num_generations: 8
  max_completion_length: 100
  beta: 0.04
  learning_rate: 0.000005
  mu: 1
  epsilon: 0.1


lora_config:
  r: 8
  lora_alpha: 32
  target_modules:
    - "q_proj"    # qwen
    - "v_proj"    # qwen
    # - "all-linear"
  lora_dropout: 0.1
  bias: "none"
  task_type: "CAUSAL_LM"

dataset:
  # name: "medmcqa"
  name: "medqa"
  num_eval: 1000

save:
  save_interval: 1

